language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  app: tranquil-shelf-53513
  on:
    repo: matthewreed26/thinkful-blog-api
  api_key:
    secure: hS0R1UCil/o47W/f4ezSZTjylcpn9lbarSZ9alhG40NvwBm4W2j5ZziqPBjXATdues8Fv+ROlKRLIEeMZayQmh8vskXNlIOn8Zoc+kSdKVwnzLBDe7KS+haBKohsxZEECEGI5PSBstwff+b6OGblFJVwQG3mpYN5s1h5EHzFmabdQ/ec7uJsiwhtl0TGFm/54KEgpC+tA0BVuk3O4GvaI+KZhHkj0u+VYtZZVQsccFwq5mvZrF+MGl/uzluMOa4TLWsShGapGwaOFgIawy88j22PzZbv+Opdrdp+3szXF5Qko3MXAADsSnYPxDIpiHWku/QwFSaGCjJHGeZtOIRdxsJ2s6G6Q0+yBsAIOEXMmYXA06oYltSGX9La116yXvzgMUx0bbsTl1/asU0MO6Th6vasUZPCjK/kB5lCv8OVTsa6dnbVlWggfNnOVVTjbPVsc0IxsnM97PxBCI7ta+hLbyHvxIJVD8XwRB2aSFJxt2dayz25W5CxSq30J9fW3XPY9sJBAtnp8nTKpYwebaJgdbrxkvXvIPc7M4SRN217bNmlZNL/ltqFf37X/5CwIMsD7mU8T9LAHP9InjLEX+C7Qo6lvZBsGyXPgGjp78Rz9LkXcgQs/DVT5bxEvTIFamF0kNceQxPudTmdNq+7Gn+aTojUG+Pd211kIB4DdWxLH70=
